"""macOS virtual key codes (kVK_*) for W3C ``KeyboardEvent.code`` names. Pure data."""

from __future__ import annotations

MAC_KEYCODES: dict[str, int] = {
    "KeyA": 0x00,
    "KeyS": 0x01,
    "KeyD": 0x02,
    "KeyF": 0x03,
    "KeyH": 0x04,
    "KeyG": 0x05,
    "KeyZ": 0x06,
    "KeyX": 0x07,
    "KeyC": 0x08,
    "KeyV": 0x09,
    "IntlBackslash": 0x0A,  # kVK_ISO_Section
    "KeyB": 0x0B,
    "KeyQ": 0x0C,
    "KeyW": 0x0D,
    "KeyE": 0x0E,
    "KeyR": 0x0F,
    "KeyY": 0x10,
    "KeyT": 0x11,
    "Digit1": 0x12,
    "Digit2": 0x13,
    "Digit3": 0x14,
    "Digit4": 0x15,
    "Digit6": 0x16,
    "Digit5": 0x17,
    "Equal": 0x18,
    "Digit9": 0x19,
    "Digit7": 0x1A,
    "Minus": 0x1B,
    "Digit8": 0x1C,
    "Digit0": 0x1D,
    "BracketRight": 0x1E,
    "KeyO": 0x1F,
    "KeyU": 0x20,
    "BracketLeft": 0x21,
    "KeyI": 0x22,
    "KeyP": 0x23,
    "Enter": 0x24,
    "KeyL": 0x25,
    "KeyJ": 0x26,
    "Quote": 0x27,
    "KeyK": 0x28,
    "Semicolon": 0x29,
    "Backslash": 0x2A,
    "Comma": 0x2B,
    "Slash": 0x2C,
    "KeyN": 0x2D,
    "KeyM": 0x2E,
    "Period": 0x2F,
    "Tab": 0x30,
    "Space": 0x31,
    "Backquote": 0x32,
    "Backspace": 0x33,
    "Escape": 0x35,
    "MetaRight": 0x36,
    "MetaLeft": 0x37,
    "ShiftLeft": 0x38,
    "CapsLock": 0x39,
    "AltLeft": 0x3A,
    "ControlLeft": 0x3B,
    "ShiftRight": 0x3C,
    "AltRight": 0x3D,
    "ControlRight": 0x3E,
    "NumpadDecimal": 0x41,
    "NumpadMultiply": 0x43,
    "NumpadAdd": 0x45,
    "NumLock": 0x47,  # kVK_ANSI_KeypadClear
    "NumpadDivide": 0x4B,
    "NumpadEnter": 0x4C,
    "NumpadSubtract": 0x4E,
    "Numpad0": 0x52,
    "Numpad1": 0x53,
    "Numpad2": 0x54,
    "Numpad3": 0x55,
    "Numpad4": 0x56,
    "Numpad5": 0x57,
    "Numpad6": 0x58,
    "Numpad7": 0x59,
    "Numpad8": 0x5A,
    "Numpad9": 0x5B,
    "F5": 0x60,
    "F6": 0x61,
    "F7": 0x62,
    "F3": 0x63,
    "F8": 0x64,
    "F9": 0x65,
    "F11": 0x67,
    "F10": 0x6D,
    "F12": 0x6F,
    "Insert": 0x72,  # kVK_Help
    "Home": 0x73,
    "PageUp": 0x74,
    "Delete": 0x75,  # kVK_ForwardDelete
    "F4": 0x76,
    "End": 0x77,
    "F2": 0x78,
    "PageDown": 0x79,
    "F1": 0x7A,
    "ArrowLeft": 0x7B,
    "ArrowRight": 0x7C,
    "ArrowDown": 0x7D,
    "ArrowUp": 0x7E,
}

# Hotkey key names -> code names (letters/digits are derived).
HOTKEY_NAMES: dict[str, str] = {
    "escape": "Escape",
    "esc": "Escape",
    "space": "Space",
    "enter": "Enter",
    "return": "Enter",
    "tab": "Tab",
    "backspace": "Backspace",
    "delete": "Delete",
    "insert": "Insert",
    "home": "Home",
    "end": "End",
    "pageup": "PageUp",
    "pagedown": "PageDown",
    "left": "ArrowLeft",
    "right": "ArrowRight",
    "up": "ArrowUp",
    "down": "ArrowDown",
    **{f"f{n}": f"F{n}" for n in range(1, 13)},
}


def code_for_hotkey_name(name: str) -> str:
    name = name.lower()
    if name in HOTKEY_NAMES:
        return HOTKEY_NAMES[name]
    if len(name) == 1 and name.isalpha():
        return f"Key{name.upper()}"
    if len(name) == 1 and name.isdigit():
        return f"Digit{name}"
    raise ValueError(f"unknown hotkey key {name!r}")
